SELECT
    REPORT_DATE,
    SEC_ACC_NO,
    DATA_SRC_PRIMARY,
    SUM(RPNL) AS RPNL,
FROM TEAMS_PRD.RISK_FUNCTION_SOURCE.SRC_CURR__RISK_FUNCTION__MRM_TRADING_BOOK_PNL
WHERE 
    SEC_ACC_NO = 9800001601
    AND REPORT_DATE >= '2026-04-01'
    AND DATA_SRC_PRIMARY = 'inquisitor_daily_reset'
GROUP BY
    REPORT_DATE,
    SEC_ACC_NO,
    DATA_SRC_PRIMARY;