-- GENERIC INSTRUMET INFO
with SECS_INFO_0 as (
SELECT 
    SECS.INSTRUMENT_ID,
    SECS.INSTRUMENT_TYPE,
    SECS.NAME_SHORT,
    SECS.NAME_OFFICIAL,
    SECS.INDEX_NAME AS STOCK_INDEX_NAME
FROM 
    TEAMS_PRD.CORE_MART.MRT_CURR__INSTRUMENTS AS SECS
),
-- WM DATA
SECS_INFO_1 as (
SELECT
    WM."isin" AS INSTRUMENT_ID,
    WM.gd172::text AS CURRENCY,
    WM.gd161::text AS COUNTRY,
    WM.gd162::text AS ISSUER_COUNTRY
FROM
    teams_prd.source_instrument_partners.src__instrument_partners__wmdaten_instruments_view AS WM
WHERE
    WM."isin" in (SELECT SECS_INFO_0.INSTRUMENT_ID FROM SECS_INFO_0)
)

SELECT
    SECS_INFO_0.INSTRUMENT_ID,
    SECS_INFO_0.NAME_SHORT,
    SECS_INFO_0.NAME_OFFICIAL,
    SECS_INFO_0.INSTRUMENT_TYPE,
    SECS_INFO_1.CURRENCY,
    SECS_INFO_1.COUNTRY,
    SECS_INFO_1.ISSUER_COUNTRY,
    SECS_INFO_0.STOCK_INDEX_NAME
FROM
    SECS_INFO_0 AS SECS_INFO_0
    LEFT JOIN
        SECS_INFO_1
    ON
        SECS_INFO_1.INSTRUMENT_ID = SECS_INFO_0.INSTRUMENT_ID
WHERE
    SECS_INFO_1.CURRENCY='RUB' OR SECS_INFO_1.COUNTRY='RU';


SELECT
    *
FROM
    TEAMS_PRD.SOURCE_PORTFOLIO.SRC__DIM__PORTFOLIO__POSITION LIMIT 10;

SELECT
    *
FROM
    TEAMS_PRD.CORE_MART.MRT_CURR__AUC
WHERE
    CALENDAR_DATE=CURRENT_DATE()-1
AND
    JURISDICTION='NL'
AND
    INSTRUMENT_TYPE='CRYPTO';