SELECT
    EXP.REPORT_DATE,
    EXP.SEC_ACC_NO,
    PRICES.INSTRUMENT_TYPE,
    EXP.INSTRUMENT_ID,
    PRICES.CLOSE_MID_PRICE_CLEAN,
    EXP.QUANTITY,
    (PRICES.CLOSE_MID_PRICE_CLEAN*EXP.QUANTITY) AS MKT_EUR
FROM
    TEAMS_PRD.RISK_FUNCTION_TRANSFORM.TRF__RISK_FUNCTION_MRM_BOOK_TOTAL_EXPOSURES EXP
LEFT JOIN
    (SELECT 
        PRX.REPORT_DATE,  -- Added this
        PRX.INSTRUMENT_ID,
        PRX.INSTRUMENT_TYPE,
        PRX.CLOSE_MID_PRICE_CLEAN  -- Added this
    FROM 
        TEAMS_PRD.RISK_FUNCTION_PUBLISH.PBL__RISK_FUNCTION_MRM_BOOK_MSL_PRICES PRX 
    WHERE 
        PRX.REPORT_DATE>'2024-01-01') AS PRICES
    ON
        PRICES.REPORT_DATE=EXP.REPORT_DATE AND PRICES.INSTRUMENT_ID=EXP.INSTRUMENT_ID
WHERE
    EXP.REPORT_DATE>'2024-01-01';



SELECT 
    *
FROM 
    TEAMS_PRD.RISK_FUNCTION_TRANSFORM.TRF__RISK_FUNCTION_MRM_BOOK_TOTAL_EXPOSURES
WHERE
    REPORT_DATE='2025-02-28';


SELECT 
    *
FROM 
    TEAMS_PRD.RISK_FUNCTION_PUBLISH.PBL__RISK_FUNCTION_FX__FX_EXPOSURE_CURRENCY_SPLIT
WHERE 
    REPORT_DATE>='2020-01-01'
AND
    CURRENCY IN ('RUB','UAH')
AND
    ACCOUNT_TYPE='Securities Services Accounts'
ORDER BY 1 DESC;


SELECT
    *
FROM
    TEAMS_PRD.CORE_MART.MRT_CURR__AUC
WHERE
    instrument_id in ('US8766292051')
AND
    calendar_date='2025-02-28'
ORDER BY 3;