with ALL_SYMBOLS as (
-- GET UNIQUE INDEX
SELECT 
    REPORT_DATE,
    INSTRUMENT_ID
FROM 
    CLONE_FABIO_BALLONI_PRD.RISK_FUNCTION_TRANSFORM.TRF__RISK_FUNCTION_MRM_BOOK_TOTAL_EXPOSURES
WHERE
    REPORT_DATE = '2025-02-18'
-- Remove Duplicates
QUALIFY ROW_NUMBER() OVER(PARTITION BY INSTRUMENT_ID,REPORT_DATE ORDER BY REPORT_DATE ASC) = 1
ORDER BY 1 DESC
),

-- GENERIC INSTRUMET INFO
SECS_INFO_0 as (
SELECT 
    SECS.INSTRUMENT_ID,
    SECS.INSTRUMENT_TYPE,
    SECS.NAME_SHORT,
    SECS.NAME_OFFICIAL,
    SECS.INDEX_NAME AS STOCK_INDEX_NAME
FROM 
    TEAMS_PRD.CORE_MART.MRT_CURR__INSTRUMENTS AS SECS
WHERE
    SECS.INSTRUMENT_ID in (SELECT ALL_SYMBOLS.INSTRUMENT_ID FROM ALL_SYMBOLS)
),

-- BOND INFO
SECS_INFO_1 as (
SELECT 
    BONDS_INFO."isin" AS INSTRUMENT_ID,
    CONCAT('BOND_',BONDS_ISSUER_INFO."issuer_classification") AS ASSET_TYPE,
    BONDS_ISSUER_INFO."issuer_name" AS ISSUER_NAME,
    BONDS_INFO."interest_period" AS INTEREST_PERIOD,
    BONDS_INFO."last_coupon_date" AS LAST_COUPON_DATE,
    BONDS_INFO."interest_rate" AS COUPON,
    BONDS_INFO."accrued_interest" AS ACCRUED_INTEREST,
    BONDS_INFO."emission_date" AS EMISSION_DATE,
    BONDS_INFO."maturity_date" AS MATURITY_DATE,
    BONDS_INFO."next_coupon_date" AS NEXT_COUPON_DATE,
    -- Trading
    BONDS_INFO."emission_volume" AS EMISSION_VOLUME,
    BONDS_INFO."min_nominal_amount" AS MIN_NOMIAL_AMOUNT,
    BONDS_INFO."step_nominal_amount" AS STEP_NOMINAL_AMOUNT
FROM 
    BACKEND_PRD.INSTRUMENT_UNIVERSE.ANONYMIZED_INSTRUMENTS__BOND AS BONDS_INFO
    INNER JOIN 
        BACKEND_PRD.INSTRUMENT_UNIVERSE.ANONYMIZED_INSTRUMENTS__ISSUER AS BONDS_ISSUER_INFO
    ON 
        BONDS_ISSUER_INFO."lei" = BONDS_INFO."issuer_lei"
WHERE
    BONDS_INFO."isin" in (SELECT ALL_SYMBOLS.INSTRUMENT_ID FROM ALL_SYMBOLS)
),

-- WM DATA
    SECS_INFO_2 as (
    SELECT
        WM."isin" AS INSTRUMENT_ID,
        WM.gd172::text AS CURRENCY,
        WM.gd161::text AS COUNTRY,
        WM.gd162::text AS ISSUER_COUNTRY
    FROM
        teams_prd.source_instrument_partners.src__instrument_partners__wmdaten_instruments_view AS WM
    WHERE
        WM."isin" in (SELECT ALL_SYMBOLS.INSTRUMENT_ID FROM ALL_SYMBOLS)
    ),

-- RATING DATA
SECS_INFO_3 as (
SELECT
    RAT.INSTRUMENT_ID AS INSTRUMENT_ID,
    RAT.RATING_SP AS RATING_SP,
    RAT.RATING_SP AS RATING_MOODYS,
    -- Map High Yield and Investment Grade
    CASE
        WHEN RAT_SCALE.RATING_NUM <= 50 THEN 'HY'
        WHEN RAT_SCALE.RATING_NUM > 50 THEN 'IG'
        ELSE NULL
    END AS RATING_GROUP,
    RAT_SCALE.RATING_NUM AS RATING_NUM,
    RAT_SCALE.RATING_CLASS AS RATING_CLASS
FROM
    TEAMS_PRD.RISK_DATA.RISK_FACTOR_BOND_RATINGS AS RAT
    LEFT JOIN
        (SELECT RATING_SP,RATING_NUM,RATING_CLASS FROM TEAMS_PRD.RISK_DATA.RISK_FACTOR_RATING_SCALE) AS RAT_SCALE
    ON RAT_SCALE.RATING_SP = RAT.RATING_SP
),      


-- SPECIFIC FUND UNDERLYING INFO 1
SECS_INFO_4 AS (
SELECT
    "instrument_isin" as instrument_id,
    "index_slug" as stock_idx_parent_name
FROM
    BACKEND_PRD.INSTRUMENT_UNIVERSE.ANONYMIZED_INSTRUMENTS__INSTRUMENT_INDEX
WHERE
    "instrument_isin" in (SELECT INSTRUMENT_ID FROM ALL_SYMBOLS)),

-- SPECIFIC FUND UNDERLYING INFO 2
SECS_INFO_5 AS (
SELECT
    "isin" as INSTRUMENT_ID,
    "underlying_class" as FUND_INSTRUMENT_TYPE,
    "index" as FUND_IDX_PARENT_NAME
FROM
    BACKEND_PRD.INSTRUMENT_UNIVERSE.ANONYMIZED_INSTRUMENTS__FUND
WHERE
    "isin" in (SELECT INSTRUMENT_ID FROM ALL_SYMBOLS)
)
    
    
SELECT
    ALL_SYMS.*,
    SECS_INFO_0.NAME_SHORT,
    SECS_INFO_0.NAME_OFFICIAL,
    SECS_INFO_0.INSTRUMENT_TYPE,
    SECS_INFO_2.CURRENCY,
    SECS_INFO_2.COUNTRY,
    SECS_INFO_2.ISSUER_COUNTRY,
    SECS_INFO_0.STOCK_INDEX_NAME,
    COALESCE(SECS_INFO_4.STOCK_IDX_PARENT_NAME,SECS_INFO_5.FUND_IDX_PARENT_NAME) as FUND_UNDERLYING_INDEX,
    CASE 
        WHEN SECS_INFO_0.INSTRUMENT_TYPE='STOCK' THEN 'EQUITY'
        WHEN SECS_INFO_0.INSTRUMENT_TYPE='FUND' THEN CONCAT('FUND_',SECS_INFO_5.FUND_INSTRUMENT_TYPE)
        WHEN SECS_INFO_0.INSTRUMENT_TYPE NOT IN ('FUND','STOCK','BOND') THEN 'STOCK'
        ELSE SECS_INFO_1.ASSET_TYPE
    END AS ASSET_TYPE,
    SECS_INFO_1.ISSUER_NAME,
    SECS_INFO_3.RATING_SP AS RATING_SP,
    SECS_INFO_3.RATING_SP AS RATING_MOODYS,
    SECS_INFO_3.RATING_NUM AS RATING_NUM,
    SECS_INFO_3.RATING_GROUP AS RATING_GROUP,
    SECS_INFO_3.RATING_CLASS AS RATING_CLASS,
    SECS_INFO_1.INTEREST_PERIOD,
    SECS_INFO_1.COUPON,
    SECS_INFO_1.ACCRUED_INTEREST AS ACCRUED_INTEREST,
    SECS_INFO_1.EMISSION_DATE,
    SECS_INFO_1.MATURITY_DATE,
    DIV0(SECS_INFO_1.MATURITY_DATE - current_date(), 365) as YEARS_TO_MATURITY,
    SECS_INFO_1.NEXT_COUPON_DATE,
    SECS_INFO_1.LAST_COUPON_DATE,
    -- Trading
    SECS_INFO_1.EMISSION_VOLUME,
    SECS_INFO_1.MIN_NOMIAL_AMOUNT,
    SECS_INFO_1.STEP_NOMINAL_AMOUNT,
    IFF(SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND', 1, 0) AS IS_ZEROCPN,
    CONCAT(
    'msl-info-',
    to_char(ALL_SYMS.REPORT_DATE, 'yyyymmdd'),
    '-',
    coalesce(to_char(ALL_SYMS.INSTRUMENT_ID), '')
    ) as surrogate_key
FROM
    ALL_SYMBOLS AS ALL_SYMS
    LEFT JOIN
        SECS_INFO_0
    ON
        SECS_INFO_0.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID
    LEFT JOIN
        SECS_INFO_1
    ON
        SECS_INFO_1.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID
    LEFT JOIN
        SECS_INFO_2
    ON
        SECS_INFO_2.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID
    LEFT JOIN
        SECS_INFO_3
    ON
        SECS_INFO_3.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID
    LEFT JOIN
        SECS_INFO_4
    ON
        SECS_INFO_4.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID 
    LEFT JOIN
        SECS_INFO_5
    ON
        SECS_INFO_5.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID;