with ALL_SYMBOLS as (
-- GET UNIQUE INDEX
SELECT 
    REPORT_DATE,
    INSTRUMENT_ID
FROM 
    CLONE_FABIO_BALLONI_PRD.RISK_FUNCTION_TRANSFORM.TRF__RISK_FUNCTION_MRM_BOOK_TOTAL_EXPOSURES
-- Remove Duplicates
QUALIFY ROW_NUMBER() OVER(PARTITION BY INSTRUMENT_ID,REPORT_DATE ORDER BY REPORT_DATE ASC) = 1
ORDER BY 1 DESC
),

-- GENERIC INSTRUMET INFO
SECS_INFO_0 as (
SELECT 
    SECS.INSTRUMENT_ID,
    SECS.INSTRUMENT_TYPE,
    SECS.NAME_SHORT,
    SECS.NAME_OFFICIAL,
    SECS.INDEX_NAME AS STOCK_INDEX_NAME
FROM 
    TEAMS_PRD.CORE_MART.MRT_CURR__INSTRUMENTS AS SECS
WHERE
    SECS.INSTRUMENT_ID in (SELECT ALL_SYMBOLS.INSTRUMENT_ID FROM ALL_SYMBOLS)
),

-- EOD Prices
EOD_PRICES as (
SELECT
    PR.CALENDAR_DATE as DDATE, 
    PR.INSTRUMENT_ID as INSTRUMENT_ID,
    PR.CLOSE_MID_PRICE AS CLOSE_MID_PRICE,
    PR.CLOSE_BID_PRICE AS CLOSE_BID_PRICE,
    PR.CLOSE_ASK_PRICE AS CLOSE_ASK_PRICE
FROM 
    TEAMS_PRD.CORE_MART.MRT_SNAPSHOT__INSTRUMENT_PRICES__EOD_PRICE as PR
WHERE
    pr.EXCHANGE = 'LSX'
AND
    PR.INSTRUMENT_ID in (SELECT ALL_SYMBOLS.INSTRUMENT_ID FROM ALL_SYMBOLS)
ORDER BY 1,2
),

-- BOND INFO
SECS_INFO_1 as (
SELECT 
    BONDS_INFO."isin" AS INSTRUMENT_ID,
    BONDS_INFO."interest_rate" AS COUPON,
    BONDS_INFO."accrued_interest" AS ACCRUED_INTEREST,
    BONDS_INFO."maturity_date" AS MATURITY_DATE
FROM 
    BACKEND_PRD.INSTRUMENT_UNIVERSE.ANONYMIZED_INSTRUMENTS__BOND AS BONDS_INFO
WHERE
    BONDS_INFO."isin" in (SELECT ALL_SYMBOLS.INSTRUMENT_ID FROM ALL_SYMBOLS)
)
    
SELECT
    ALL_SYMS.*,
    SECS_INFO_0.NAME_SHORT,
    SECS_INFO_0.NAME_OFFICIAL,
    SECS_INFO_0.INSTRUMENT_TYPE,
    SECS_INFO_1.ACCRUED_INTEREST AS ACCRUED_INTEREST,
    DIV0(SECS_INFO_1.MATURITY_DATE - current_date(), 365) as YEARS_TO_MATURITY,
    -- Aggregates
    IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_MID_PRICE, 100), EOD_PRICES.CLOSE_MID_PRICE)  AS CLOSE_MID_PRICE_CLEAN,
    IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_BID_PRICE, 100), EOD_PRICES.CLOSE_BID_PRICE)  AS CLOSE_BID_PRICE_CLEAN,
    IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_ASK_PRICE, 100), EOD_PRICES.CLOSE_ASK_PRICE)  AS CLOSE_ASK_PRICE_CLEAN,
    CASE
        WHEN SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND' THEN CLOSE_MID_PRICE_CLEAN
        ELSE IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_MID_PRICE+ACCRUED_INTEREST, 100), EOD_PRICES.CLOSE_MID_PRICE+ACCRUED_INTEREST)
    END AS MID_PRICE_DIRTY,
    CASE
        WHEN SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND' THEN CLOSE_BID_PRICE_CLEAN
        ELSE IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_BID_PRICE+ACCRUED_INTEREST, 100), EOD_PRICES.CLOSE_BID_PRICE+ACCRUED_INTEREST)
    END AS BID_PRICE_DIRTY,
    CASE
        WHEN SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND' THEN CLOSE_ASK_PRICE_CLEAN
        ELSE IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_ASK_PRICE+ACCRUED_INTEREST, 100), EOD_PRICES.CLOSE_ASK_PRICE+ACCRUED_INTEREST)
    END AS ASK_PRICE_DIRTY,
    CASE
        WHEN SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND' THEN (DIV0((1-CLOSE_MID_PRICE_CLEAN),YEARS_TO_MATURITY))/((1+CLOSE_MID_PRICE_CLEAN)/2)
        ELSE (SECS_INFO_1.COUPON +DIV0((1-CLOSE_MID_PRICE_CLEAN),YEARS_TO_MATURITY))/((1+CLOSE_MID_PRICE_CLEAN)/2)
    END AS YIELD_TO_MATURITY,
    CASE
        WHEN SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND' THEN YIELD_TO_MATURITY
        ELSE DIV0(SECS_INFO_1.COUPON,CLOSE_MID_PRICE_CLEAN)
    END AS CURRENT_YIELD,
    CONCAT(
    'msl-',
    to_char(ALL_SYMS.report_date, 'yyyymmdd'),
    '-',
    coalesce(to_char(ALL_SYMS.INSTRUMENT_ID), '')
    ) as surrogate_key
FROM
    ALL_SYMBOLS AS ALL_SYMS
    LEFT JOIN
        SECS_INFO_0
    ON
        SECS_INFO_0.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID
    LEFT JOIN
        EOD_PRICES
    ON
        EOD_PRICES.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID AND EOD_PRICES.DDATE = ALL_SYMS.REPORT_DATE
    LEFT JOIN
        SECS_INFO_1
    ON
        SECS_INFO_1.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID;



with ALL_SYMBOLS as (
-- GET UNIQUE INDEX
SELECT 
    POS.REPORT_DATE,
    POS.INSTRUMENT_ID
FROM 
    CLONE_FABIO_BALLONI_PRD.RISK_FUNCTION_TRANSFORM.TRF__RISK_FUNCTION_MRM_BOOK_TOTAL_EXPOSURES AS POS
WHERE
    REPORT_DATE >= '2025-02-15'
-- Remove Duplicates
QUALIFY ROW_NUMBER() OVER(PARTITION BY POS.INSTRUMENT_ID,POS.REPORT_DATE ORDER BY POS.REPORT_DATE ASC) = 1
ORDER BY 1 DESC
),

-- GENERIC INSTRUMET INFO
SECS_INFO_0 as (
SELECT 
    SECS.INSTRUMENT_ID,
    SECS.INSTRUMENT_TYPE,
    SECS.NAME_SHORT,
    SECS.NAME_OFFICIAL,
    SECS.INDEX_NAME AS STOCK_INDEX_NAME
FROM 
    TEAMS_PRD.CORE_MART.MRT_CURR__INSTRUMENTS AS SECS
WHERE
    SECS.INSTRUMENT_ID in (SELECT ALL_SYMBOLS.INSTRUMENT_ID FROM ALL_SYMBOLS)
),

-- EOD Prices
EOD_PRICES as (
SELECT
    PR.CALENDAR_DATE as REPORT_DATE, 
    PR.INSTRUMENT_ID as INSTRUMENT_ID,
    PR.CLOSE_MID_PRICE AS CLOSE_MID_PRICE,
    PR.CLOSE_BID_PRICE AS CLOSE_BID_PRICE,
    PR.CLOSE_ASK_PRICE AS CLOSE_ASK_PRICE
FROM 
    TEAMS_PRD.CORE_MART.MRT_SNAPSHOT__INSTRUMENT_PRICES__EOD_PRICE as PR
WHERE
    PR.CALENDAR_DATE >= '2025-02-15'
AND
    pr.EXCHANGE = 'LSX'
AND
    PR.INSTRUMENT_ID in (SELECT ALL_SYMBOLS.INSTRUMENT_ID FROM ALL_SYMBOLS)
ORDER BY 1,2
),

-- BOND INFO
SECS_INFO_1 as (
SELECT
    BONDS_INFO."re"
    BONDS_INFO."isin" AS INSTRUMENT_ID,
    BONDS_INFO."interest_rate" AS COUPON,
    BONDS_INFO."accrued_interest" AS ACCRUED_INTEREST,
    BONDS_INFO."maturity_date" AS MATURITY_DATE
FROM 
    BACKEND_PRD.INSTRUMENT_UNIVERSE.ANONYMIZED_INSTRUMENTS__BOND AS BONDS_INFO
WHERE
    BONDS_INFO."isin" in (SELECT ALL_SYMBOLS.INSTRUMENT_ID FROM ALL_SYMBOLS)
)
    
SELECT
    ALL_SYMS.*,
    SECS_INFO_0.NAME_SHORT,
    SECS_INFO_0.NAME_OFFICIAL,
    SECS_INFO_0.INSTRUMENT_TYPE,
    SECS_INFO_1.ACCRUED_INTEREST AS ACCRUED_INTEREST,
    DIV0(SECS_INFO_1.MATURITY_DATE - current_date(), 365) as YEARS_TO_MATURITY,
    -- Aggregates
    IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_MID_PRICE, 100), EOD_PRICES.CLOSE_MID_PRICE)  AS CLOSE_MID_PRICE_CLEAN,
    IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_BID_PRICE, 100), EOD_PRICES.CLOSE_BID_PRICE)  AS CLOSE_BID_PRICE_CLEAN,
    IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_ASK_PRICE, 100), EOD_PRICES.CLOSE_ASK_PRICE)  AS CLOSE_ASK_PRICE_CLEAN,
    CASE
        WHEN SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND' THEN CLOSE_MID_PRICE_CLEAN
        ELSE IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_MID_PRICE+ACCRUED_INTEREST, 100), EOD_PRICES.CLOSE_MID_PRICE+ACCRUED_INTEREST)
    END AS MID_PRICE_DIRTY,
    CASE
        WHEN SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND' THEN CLOSE_BID_PRICE_CLEAN
        ELSE IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_BID_PRICE+ACCRUED_INTEREST, 100), EOD_PRICES.CLOSE_BID_PRICE+ACCRUED_INTEREST)
    END AS BID_PRICE_DIRTY,
    CASE
        WHEN SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND' THEN CLOSE_ASK_PRICE_CLEAN
        ELSE IFF(SECS_INFO_0.INSTRUMENT_TYPE = 'BOND',DIV0(EOD_PRICES.CLOSE_ASK_PRICE+ACCRUED_INTEREST, 100), EOD_PRICES.CLOSE_ASK_PRICE+ACCRUED_INTEREST)
    END AS ASK_PRICE_DIRTY,
    CASE
        WHEN SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND' THEN (DIV0((1-CLOSE_MID_PRICE_CLEAN),YEARS_TO_MATURITY))/((1+CLOSE_MID_PRICE_CLEAN)/2)
        ELSE (SECS_INFO_1.COUPON +DIV0((1-CLOSE_MID_PRICE_CLEAN),YEARS_TO_MATURITY))/((1+CLOSE_MID_PRICE_CLEAN)/2)
    END AS YIELD_TO_MATURITY,
    CASE
        WHEN SECS_INFO_1.COUPON IS NULL AND SECS_INFO_0.INSTRUMENT_TYPE = 'BOND' THEN YIELD_TO_MATURITY
        ELSE DIV0(SECS_INFO_1.COUPON,CLOSE_MID_PRICE_CLEAN)
    END AS CURRENT_YIELD
FROM
    ALL_SYMBOLS AS ALL_SYMS
    LEFT JOIN
        SECS_INFO_0
    ON
        SECS_INFO_0.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID
    LEFT JOIN
        EOD_PRICES
    ON
        EOD_PRICES.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID AND EOD_PRICES.REPORT_DATE = ALL_SYMS.REPORT_DATE
    LEFT JOIN
        SECS_INFO_1
    ON
        SECS_INFO_1.INSTRUMENT_ID = ALL_SYMS.INSTRUMENT_ID;


SELECT DISTINCT("extraction_timestamp"::date) FROM BACKEND_PRD.INSTRUMENT_UNIVERSE.ANONYMIZED_INSTRUMENTS__BOND LIMIT 10;