set rep_date = '2025-06-30';

-- Template 1 ----------------------------------------------------------------------------------------------------------------------


SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 WHERE REPORT_DATE=$rep_date ORDER BY IDX ;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 WHERE REPORT_DATE=$rep_date;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00
WHERE
    REPORT_DATE='2024-12-31';



UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE=NULL WHERE REPORT_DATE=$rep_date;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = 0 WHERE REPORT_DATE=$rep_date AND IDX=0010;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = 0 WHERE REPORT_DATE=$rep_date AND IDX=0020;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = 0 WHERE REPORT_DATE=$rep_date AND IDX=0030;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = 0 WHERE REPORT_DATE=$rep_date AND IDX in (0040,0050,0060,0070,0080,0090);
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = -16320946 WHERE REPORT_DATE=$rep_date AND IDX=0100;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = 0.0288 WHERE REPORT_DATE=$rep_date AND IDX=0110;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = 16713764 WHERE REPORT_DATE=$rep_date AND IDX=0120; --18817348
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = 16320946 WHERE REPORT_DATE=$rep_date AND IDX=0130; -- -12488794
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = -16320946 WHERE REPORT_DATE=$rep_date AND IDX=0140; -- 12488794
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = 817225764 WHERE REPORT_DATE=$rep_date AND IDX=0150;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = 833546711 WHERE REPORT_DATE=$rep_date AND IDX=0160;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 SET VALUE = 800904817 WHERE REPORT_DATE=$rep_date AND IDX=0170;

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 WHERE REPORT_DATE=$rep_date ORDER BY IDX;

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 WHERE REPORT_DATE='2025-03-31'ORDER BY IDX;

--DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 WHERE REPORT_DATE=$rep_date;

-- Template 3 ----------------------------------------------------------------------------------------------------------------------

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 WHERE REPORT_DATE=$rep_date;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00
WHERE
    REPORT_DATE='2024-12-31';


UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = NULL WHERE REPORT_DATE=$rep_date;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 817225764 WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0010;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 539136769 WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0010;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 278088996 WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0010;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 0.0028 WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0020;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 0.0028 WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0020;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 0.0028 WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0020;

-- New 0 Fields as interesting 0
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 
SET VALUE = 0 
WHERE REPORT_DATE=$rep_date 
AND IDX IN (0010,0030,0040) 
AND GROUP_1 IN ('0030', '0040', '0050', '0060', '0070', '0080','0090')
AND REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 16713765 WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0100;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 12061878 WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0100;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 6200641 WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0100;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 16320947 WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0110;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 10782735 WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0110;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 5538211 WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0110;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = -16320947 WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0120;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = -10782735 WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0120;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = -5538211 WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0120;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 
SET VALUE = NULL 
WHERE GROUP_1 IN ('0030', '0040', '0050', '0060', '0070', '0080','0090','0130', '0140', '0150')
AND IDX NOT IN (0010,0030,0040) 
AND REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 817225764 WHERE REPORT_DATE=$rep_date AND IDX=0570 AND GROUP_1=0130;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 833546711 WHERE REPORT_DATE=$rep_date AND IDX=0570 AND GROUP_1=0140;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 800904818 WHERE REPORT_DATE=$rep_date AND IDX=0570 AND GROUP_1=0150;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 0 WHERE REPORT_DATE=$rep_date AND IDX=0610 AND GROUP_1=0130;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 0 WHERE REPORT_DATE=$rep_date AND IDX=0610 AND GROUP_1=0140;
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 SET VALUE = 0 WHERE REPORT_DATE=$rep_date AND IDX=0610 AND GROUP_1=0150;



SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 WHERE VALUE IS NOT NULL AND REPORT_DATE=$rep_date ORDER BY IDX, GROUP_1, GROUP_0, REPORT_DATE;

SELECT IDX AS ROW_INDEX,GROUP_1 AS COLUMN_INDEX,VALUE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 WHERE REPORT_DATE=$rep_date order by 1,2;


-- Template 6 A ----------------------------------------------------------------------------------------------------------------------

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A
WHERE
    REPORT_DATE='2024-12-31';


-- idx = 0010
-- Next Only Reported in MR_IRRBB_EBA_J06_00_A
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0020; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0030; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0040;  --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0050; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0060; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = 6356 WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0070; --ok

-- idx = 0030
-- Next Only Reported in MR_IRRBB_EBA_J06_00_A
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0020; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0030; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0040;  --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0050; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0060; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = 4193 WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0070; --ok

-- idx = 0040 
-- Next Only Reported in MR_IRRBB_EBA_J06_00_A
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0020; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0030; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0040;  --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0050; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0060; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE = 2163 WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0070; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A SET VALUE=NULL WHERE VALUE=0 AND REPORT_DATE=$rep_date;

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A WHERE REPORT_DATE=$rep_date AND VALUE IS NOT NULL;


-- Template 11 1 ----------------------------------------------------------------------------------------------------------------------

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 WHERE REPORT_DATE=$rep_date;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 WHERE REPORT_DATE=$rep_date;


INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    VALUE
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01
WHERE
    REPORT_DATE='2024-12-31';

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = NULL WHERE REPORT_DATE=$rep_date AND GROUP_1=0010; --ok

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_AP:x264' WHERE REPORT_DATE=$rep_date AND IDX=0010 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_AP:x259' WHERE REPORT_DATE=$rep_date AND IDX=0020 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_ZZ:x706' WHERE REPORT_DATE=$rep_date AND IDX=0030 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_ZZ:x711' WHERE REPORT_DATE=$rep_date AND IDX=0040 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_TR:x76' WHERE REPORT_DATE=$rep_date AND IDX=0050 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_TR:x78' WHERE REPORT_DATE=$rep_date AND IDX=0060 AND GROUP_1=0010; --ok

    
-- IF ANNUAL
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_ZZ:x713' WHERE REPORT_DATE=$rep_date AND IDX=0070 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_ZZ:x718' WHERE REPORT_DATE=$rep_date AND IDX=0080 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_TR:x80' WHERE REPORT_DATE=$rep_date AND IDX=0090 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_TR:x82' WHERE REPORT_DATE=$rep_date AND IDX=0100 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_ZZ:x720' WHERE REPORT_DATE=$rep_date AND IDX=0110 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_ZZ:x722' WHERE REPORT_DATE=$rep_date AND IDX=0120 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_ZZ:x724' WHERE REPORT_DATE=$rep_date AND IDX=0130 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_IM:x118' WHERE REPORT_DATE=$rep_date AND IDX=0140 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_MC:x1304' WHERE REPORT_DATE=$rep_date AND IDX=0150 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_TR:x84' WHERE REPORT_DATE=$rep_date AND IDX=0160 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 SET VALUE = 'eba_TR:x86' WHERE REPORT_DATE=$rep_date AND IDX=0170 AND GROUP_1=0010; --ok



SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 WHERE REPORT_DATE=$rep_date;


-- Template 11 2 ----------------------------------------------------------------------------------------------------------------------

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02 WHERE REPORT_DATE=$rep_date;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02 (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    VALUE
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02
WHERE
    REPORT_DATE='2024-12-31';

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02 SET VALUE = 'eba_ZZ:x759' WHERE REPORT_DATE=$rep_date AND IDX=0320 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02 SET VALUE = 'eba_ZZ:x766' WHERE REPORT_DATE=$rep_date AND IDX=0330 AND GROUP_1=0010; --ok
UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02 SET VALUE = 'eba_ZZ:x781' WHERE REPORT_DATE=$rep_date AND IDX=0360 AND GROUP_1=0010; --ok

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02 WHERE REPORT_DATE=$rep_date;



-- Empty Tables
--
--
--
--
-- Template 2 ----------------------------------------------------------------------------------------------------------------------

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J02_00;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J02_00 SET VALUE = NULL;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J02_00 (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J02_00
WHERE
    REPORT_DATE='2024-12-31';

-- Template 4 ----------------------------------------------------------------------------------------------------------------------

SELECT DISTINCT(REPORT_DATE) FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J04_00;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J04_00 WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J04_00 SET VALUE = NULL;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J04_00 (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J04_00
WHERE
    REPORT_DATE='2024-12-31';


-- Template 5 A ----------------------------------------------------------------------------------------------------------------------

SELECT DISTINCT(REPORT_DATE) FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_A;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_A WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_A SET VALUE = NULL;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_A (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_A
WHERE
    REPORT_DATE='2024-12-31';

-- Template 5 B ----------------------------------------------------------------------------------------------------------------------

SELECT DISTINCT(REPORT_DATE) FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_B;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_B WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_B SET VALUE = NULL;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_B (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_B
WHERE
    REPORT_DATE='2024-12-31';


-- Template 6 B ----------------------------------------------------------------------------------------------------------------------

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_B;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_B WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_B SET VALUE = NULL;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_B (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_B
WHERE
    REPORT_DATE='2024-12-31';




-- Template 7 A ----------------------------------------------------------------------------------------------------------------------

SELECT DISTINCT(REPORT_DATE) FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_A;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_A WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_A SET VALUE = NULL;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_A (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_A
WHERE
    REPORT_DATE='2024-12-31';



-- Template 7 B ----------------------------------------------------------------------------------------------------------------------

SELECT DISTINCT(REPORT_DATE) FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_B;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_B WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_B SET VALUE = NULL;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_B (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_B
WHERE
    REPORT_DATE='2024-12-31';


-- Template 8 A ----------------------------------------------------------------------------------------------------------------------

SELECT DISTINCT(VALUE) FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_A;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_A WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_A SET VALUE = NULL;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_A (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_A
WHERE
    REPORT_DATE='2024-12-31';


-- Template 8 B ----------------------------------------------------------------------------------------------------------------------

SELECT DISTINCT(VALUE) FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_B;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_B WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_B SET VALUE = NULL;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_B (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_B
WHERE
    REPORT_DATE='2024-12-31';


-- Template 9 A ----------------------------------------------------------------------------------------------------------------------

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_A WHERE REPORT_DATE=$rep_date;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_A WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_A SET VALUE = 0 WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_A SET VALUE = NULL WHERE GROUP_1='0020' AND REPORT_DATE=$rep_date;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_A (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_A
WHERE
    REPORT_DATE='2024-12-31';

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_A WHERE REPORT_DATE=$rep_date;


-- Template 9 B ----------------------------------------------------------------------------------------------------------------------

SELECT DISTINCT(VALUE) FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_B;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_B WHERE REPORT_DATE=$rep_date;

UPDATE TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_B SET VALUE = NULL WHERE REPORT_DATE=$rep_date;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_B (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_B
WHERE
    REPORT_DATE='2024-12-31';

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_B WHERE REPORT_DATE=$rep_date;



-- Template 10 1 ----------------------------------------------------------------------------------------------------------------------

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_01;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_01 WHERE REPORT_DATE=$rep_date;


INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_01 (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_01
WHERE
    REPORT_DATE='2024-12-31';


-- Template 10 2 ----------------------------------------------------------------------------------------------------------------------

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_02;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_02 WHERE REPORT_DATE=$rep_date;

INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_02 (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_02
WHERE
    REPORT_DATE='2024-12-31';

-- Template 11 1 ----------------------------------------------------------------------------------------------------------------------

SELECT * FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01;

DELETE FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 WHERE REPORT_DATE=$rep_date;


INSERT INTO TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 (REPORT_DATE, IDX, GROUP_0, GROUP_1, FMT, VALUE)
SELECT 
    $rep_date, 
    IDX, 
    GROUP_0, 
    GROUP_1, 
    FMT, 
    NULL
FROM 
    TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01
WHERE
    REPORT_DATE='2024-09-30';




