SELECT column_name, data_type, is_nullable
FROM TEAMS_PRD.INFORMATION_SCHEMA.COLUMNS
WHERE table_schema = 'RISK_DATA'
  AND table_name = 'MR_IRRBB_EBA_J01_00'
ORDER BY ordinal_position;


SELECT 'J_01_00' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00

UNION ALL

SELECT 'J_02_00' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J02_00

UNION ALL

SELECT 'J_03_00' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00

UNION ALL

SELECT 'J_04_00' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J04_00

UNION ALL

SELECT 'J_05_00_A' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_A

UNION ALL

SELECT 'J_05_00_B' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_B

UNION ALL

SELECT 'J_06_00_A' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A

UNION ALL

SELECT 'J_06_00_B' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_B

UNION ALL

SELECT 'J_07_00_A' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_A

UNION ALL

SELECT 'J_07_00_B' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_B

UNION ALL

SELECT 'J_08_00_A' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_A

UNION ALL

SELECT 'J_08_00_B' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_B

UNION ALL

SELECT 'J_09_00_A' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_A

UNION ALL

SELECT 'J_09_00_B' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_B

UNION ALL

SELECT 'J_10_01' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_01

UNION ALL

SELECT 'J_10_02' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_02

UNION ALL

SELECT 'J_11_01' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, NULL
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01

UNION ALL

SELECT 'J_11_02' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, NULL
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02;


SELECT 'J_01_00' AS REPORT, IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J01_00 WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_02_00', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J02_00 WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_03_00', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J03_00 WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_04_00', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J04_00 WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_05_00_A', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_A WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_05_00_B', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J05_00_B WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_06_00_A', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_A WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_06_00_B', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J06_00_B WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_07_00_A', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_A WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_07_00_B', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J07_00_B WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_08_00_A', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_A WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_08_00_B', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J08_00_B WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_09_00_A', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_A WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_09_00_B', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J09_00_B WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_10_01', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_01 WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_10_02', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J10_02 WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_11_01', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01 WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL
UNION ALL
SELECT 'J_11_02', IDX FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02 WHERE TRY_TO_NUMBER(IDX::VARCHAR) IS NULL;



SELECT 'J_11_01' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE 
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_01
UNION ALL
SELECT 'J_11_02' AS REPORT, REPORT_DATE, IDX::VARCHAR, GROUP_0, GROUP_1, FMT, VALUE 
FROM TEAMS_PRD.RISK_DATA.MR_IRRBB_EBA_J11_02;






with unioned_data as (
SELECT
*
FROM
TEAMS_PRD.RISK_FUNCTION_TRANSFORM.trf__risk_function_mrm_book_9800006001_daily_exposures--trf__risk_function_mrm_book_total_exposures--
)

select
  distinct(report_date)
from
    unioned_data as pos
WHERE
    pos.report_date <= current_date - 1
and
    dayofweek(pos.report_date) not in (0,6,7)
ORDEr BY 1 DESC;

SELECT
REPORT_DATE,
COUNT(distinct SEC_ACC_NO)
FROM
TEAMS_PRD.RISK_FUNCTION_TRANSFORM.trf__risk_function_mrm_book_total_exposures
GROUP BY 1
ORDER BY 1 DESC;






SELECT
DISTINCT(TRADING_ACCOUNT)
FROM BACKEND_PRD.TROMSO.executions_v0_4;


SELECT
DISTINCT(TRADING_ACCOUNT)
FROM BACKEND_PRD.TROMSO.positions_v0_2;

SELECT
*
FROM TEAMS_PRD.RISK_FUNCTION_PUBLISH.pbl__risk_function_mrm_book_trading_valuation_intraday;





with unioned_data as (
    select
        *
    from
        TEAMS_PRD.risk_function_transform.trf__risk_function_mrm_book_9800001301_daily_exposures

    union all

    select
        *
    from
        TEAMS_PRD.risk_function_transform.trf__risk_function_mrm_book_9800001601_daily_exposures

    union all

    select
        *
    from
        TEAMS_PRD.risk_function_transform.trf__risk_function_mrm_book_9800003301_daily_exposures

    union all

    select
        *
    from
        TEAMS_PRD.risk_function_transform.trf__risk_function_mrm_book_9800003601_daily_exposures

    union all

    select
        *
    from
        TEAMS_PRD.risk_function_transform.trf__risk_function_mrm_book_9800005001_daily_exposures

    union all

    select
        *
    from
        TEAMS_PRD.risk_function_transform.trf__risk_function_mrm_book_9800005201_daily_exposures

    union all

    select
        *
    from
        TEAMS_PRD.risk_function_transform.trf__risk_function_mrm_book_9800005401_daily_exposures

    union all

    select
        *
    from
        TEAMS_PRD.risk_function_transform.trf__risk_function_mrm_book_9800005901_daily_exposures

    union all

    select
        *
    from
        TEAMS_PRD.risk_function_transform.trf__risk_function_mrm_book_9800006001_daily_exposures
),

out as (
SELECT
u.REPORT_DATE,
COUNT(distinct u.SEC_ACC_NO) AS QUERY,
COUNT(distinct p.SEC_ACC_NO) AS DBT
FROM
unioned_data u
FULL JOIN (
  SELECT
  REPORT_DATE,
  SEC_ACC_NO
  FROM
  TEAMS_PRD.RISK_FUNCTION_TRANSFORM.trf__risk_function_mrm_book_total_exposures
) as p
ON p.REPORT_DATE = u.REPORT_DATE
WHERE
u.REPORT_DATE<= CURRENT_DATE -1
GROUP BY 1
ORDER BY 1 DESC)

SELECT
out.*,
dayofweek(out.REPORT_DATE)
FROM out;


SELECT
report_date,
SUM(abs(mkt_mid_eur)) AS gross_exposure 
FROM TEAMS_PRD.RISK_FUNCTION_PUBLISH.pbl__risk_function_mrm_book_trading_valuation
WHERE  
1=1
AND
report_date='2026-05-08'
AND DAYOFWEEK(report_date) NOT IN (0, 6, 7) 
and sec_acc_no= '9800006001'
GROUP BY --sec_acc_no, 
report_date
order by report_date;


select
    pos.report_date,
    pos.sec_acc_no,
    pos.instrument_id,
    pos.quantity,
    pos.surrogate_key,
    pos.data_src_primary
from
    unioned_data as pos
WHERE
    pos.report_date <= current_date - 1
and
    dayofweek(pos.report_date) not in (0,6,7)














WITH daily AS (
    SELECT
        date                            AS report_date,
        SUM(DAILYPNL)                   AS daily_pnl,
        SUM(ABSCUSTOMERTRADEDVOLUME)    AS volume_eur
    FROM TIBERIUS_PRD.TRADING_PLATFORM_EXTERNAL_SOURCES.MM_INQUISITOR_DAILY_PNL_METRICS
    WHERE date >= '2026-01-01'      -- 90d + 6d buffer for the 7d window
      AND tradingaccount = 200
    GROUP BY 1
)
SELECT
    report_date,
    SUM(daily_pnl) OVER (ORDER BY report_date ASC) AS rolling_pnl,
    volume_eur
FROM daily
WHERE
volume_eur <> 0
ORDER BY 1;


WITH daily AS (
  SELECT
    date,
    tradingaccount,
    SUM(DAILYPNL) AS pnl,
    SUM(ABSCUSTOMERTRADEDVOLUME) AS vol
  FROM TIBERIUS_PRD.TRADING_PLATFORM_EXTERNAL_SOURCES.MM_INQUISITOR_DAILY_PNL_METRICS
  WHERE date >= '2025-12-31'      -- 90d + 6d buffer for the 7d window
    AND tradingaccount = 200
  GROUP BY GROUPING SETS ((date, tradingaccount), (date))  -- adds ALL_ACCOUNTS rows
),
roll AS (
  SELECT
    date,
    tradingaccount,  -- NULL here represents ALL_ACCOUNTS
    SUM(pnl) OVER (
      PARTITION BY tradingaccount
      ORDER BY date
      RANGE BETWEEN INTERVAL '7 DAY' PRECEDING AND CURRENT ROW
    ) AS r_pnl,
    SUM(vol) OVER (
      PARTITION BY tradingaccount
      ORDER BY date
      RANGE BETWEEN INTERVAL '7 DAY' PRECEDING AND CURRENT ROW
    ) AS r_vol
  FROM daily
)
SELECT
  date,
  CASE WHEN tradingaccount IS NULL THEN 'ALL_ACCOUNTS' ELSE 'BY_ACCOUNT' END AS scope,
  tradingaccount,
  IFF(r_vol = 0, 0, 10000 * r_pnl / r_vol) AS Rolling7dPnLBPS
FROM roll
WHERE date > '2025-12-31'
ORDER BY date DESC, scope, tradingaccount;


SELECT
*
FROM
TEAMS_PRD.RISK_FUNCTION_TRANSFORM.trf__risk_function_mrm_book_9800006001_daily_exposures
WHERE
REPORT_DATE='2026-05-08'
ORDER BY 1;


SELECT
MAX(SEQ_DATE)
FROM
BACKEND_PRD.TROMSO.positions_v0_2
;


SELECT
*
FROM TEAMS_PRD.RISK_FUNCTION_PUBLISH.pbl__risk_function_mrm_book_trading_valuation
WHERE
REPORT_DATE='2026-05-08'
AND
SEC_ACC_NO='9800006001';

